name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - java-version: '8'
            gradle-version: '6.9.4'
          - java-version: '8'
            gradle-version: '7.6.6'
          - java-version: '8'
            gradle-version: '8.14.4'
          - java-version: '17'
            gradle-version: '9.4.1'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: temurin
          architecture: x64

      - name: Validate Wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      #- name: Generate and submit dependency graph
      #  uses: gradle/actions/dependency-submission@v5

      - name: Build with Gradle
        run: ./gradlew check -PgradleVersion=${{ matrix.gradle-version }} -PjavaVersion=${{ matrix.java-version }}

      - name: Upload Test Report
        uses: actions/upload-artifact@v7
        if: always() # always run even if the previous step fails
        with:
          name: junit-test-results-${{ matrix.gradle-version }}
          path: '**/build/test-results/test/TEST-*.xml'
          retention-days: 1
